import _ from 'lodash'

const base = {
  id: null,
  etype: null,
  edeviceNo: null,
  ename: null,
  edeptId: null,
  craftsId: null,
  dailyEnergy: null,
  status: null,
  deptParentId: null,
  remark: null,
  speed: null,
  ebrand: null,
  emachineType: null,
  edition: null,
  enetworkAddress: null,
  ftpName: null,
  ftpPwd: null,
  isAutomation: null,
  isUse: null,
  ezhixi: null,
  eacceptanceDate: null,
  esection: null,
  edeviceCode: null,
  efactory: null,
  edistrict: null,
  emaintianPersonId: null,
  eresponsiblePersonId: null,
  eresponsibleDept: null,
  eprocessDept: null,
  eproductDept: null,
  eproductCode: null,
  eproductDate: null,
  eenterDate: null,
  echeckDate: null,
  epower: null,
  erepairDept: null,
  erepairManagerId: null,
  estorageArea: null,
  estoragePosition: null,
  eassetNumber: null,
  ecompany: null,
  eisonline: null,
  eisdigit: null,
  eprecision: null,
  esize: null,
  exstroke: null,
  eystroke: null,
  ezstroke: null,
  eustroke: null,
  evstroke: null,
  erotateSpeed: null,
  epushSpeed: null,
  eweight: null,
  evoltage: null,
  eairPressure: null,
  eknifeCapacity: null,
  econtroller: null,
  eversion: null,
  eiceMachineBrand: null,
  eiceMachineModel: null,
  eiceMachineNumber: null,
  eiceMachinePower: null,
  createBy: null,
  createTime: null,
  updateTime: null,
  updateBy: null

}

const queryEmpty = {
  eDeptId: null,
  eProductCode: null,
  eDeviceNo: null,
  eZhixi: null,
  eFactory: null,
  eProcessDept: null
}

const query = _.cloneDeep(queryEmpty)

// 查询提交数据，查询前进行同步
const queryReal = _.cloneDeep(queryEmpty)

const create = _.cloneDeep(base)

// create提交数据，属性值务必准确，多余属性不会提交
const createReal = { companyId: null, type: null, name: null, remark: null, accesses: null }

const update = _.cloneDeep(base)

// update提交数据，属性值务必准确，多余属性不会提交
const updateReal = {
  id: null,
  etype: null,
  edeviceNo: null,
  ename: null,
  edeptId: null,
  craftsId: null,
  dailyEnergy: null,
  status: null,
  deptParentId: null,
  remark: null,
  speed: null,
  ebrand: null,
  emachineType: null,
  edition: null,
  enetworkAddress: null,
  ftpName: null,
  ftpPwd: null,
  isAutomation: null,
  isUse: null,
  ezhixi: null,
  eacceptanceDate: null,
  esection: null,
  edeviceCode: null,
  efactory: null,
  edistrict: null,
  emaintianPersonId: null,
  eresponsiblePersonId: null,
  eresponsibleDept: null,
  eprocessDept: null,
  eproductDept: null,
  eproductCode: null,
  eproductDate: null,
  eenterDate: null,
  echeckDate: null,
  epower: null,
  erepairDept: null,
  erepairManagerId: null,
  estorageArea: null,
  estoragePosition: null,
  eassetNumber: null,
  ecompany: null,
  eisonline: null,
  eisdigit: null,
  eprecision: null,
  esize: null,
  exstroke: null,
  eystroke: null,
  ezstroke: null,
  eustroke: null,
  evstroke: null,
  erotateSpeed: null,
  epushSpeed: null,
  eweight: null,
  evoltage: null,
  eairPressure: null,
  eknifeCapacity: null,
  econtroller: null,
  eversion: null,
  eiceMachineBrand: null,
  eiceMachineModel: null,
  eiceMachineNumber: null,
  eiceMachinePower: null,
  createBy: null,
  createTime: null,
  updateTime: null,
  updateBy: null
}

const detail = _.cloneDeep(base)

export default { queryEmpty, query, queryReal, create, createReal, update, updateReal, detail }

